In [1]:
# importing packages
import pandas as pd
import numpy as np
import os
import platform
import pingouin as pg
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels as sm
import pyreadstat

In [2]:
#opening file
df=pd.read_csv("PilotData/us-presidential-tweet-id-2019-12-01-00.csv", low_memory=False)

In [3]:
#checking file
df

,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_user_id,...,user_followers_count,user_friends_count,user_listed_count,user_location,user_name,user_screen_name,user_statuses_count,user_time_zone,user_urls,user_verified
0,NaN,Sun Dec 01 00:00:02 +0000 2019,NaN,NaN,NaN,0,1200927498504200192,KamalaHarris,1.200536e+18,3.035499e+07,...,209,186,2,NaN,Diane Carrozza,DianeEllenC,13719,NaN,NaN,False
1,NaN,Sun Dec 01 00:00:01 +0000 2019,NaN,NaN,NaN,0,1200927496386035714,NaN,NaN,NaN,...,1473,3290,18,"Manhattan, NY",Things Trump Say,thingstrumpsay,154463,NaN,NaN,False
2,NaN,Sun Dec 01 00:00:00 +0000 2019,NaN,NaN,NaN,0,1200927489792626688,LeaderMcConnell,1.200774e+18,1.249982e+09,...,5,173,0,"Georgia, USA",AJS,AndrewJSheldon,209,NaN,NaN,False
3,NaN,Sun Dec 01 00:00:00 +0000 2019,ImpeachTheMFTraitorNow,NaN,NaN,0,1200927490434359300,realDonaldTrump,1.200918e+18,2.507388e+07,...,2246,2108,0,NaN,VAgirl,agirrrl,30890,NaN,NaN,False
4,NaN,Sun Dec 01 00:00:00 +0000 2019,NaN,NaN,NaN,0,1200927489821986817,realDonaldTrump,1.200869e+18,2.507388e+07,...,31,61,0,NaN,Catherine Schuchman,greyz67,1130,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39505,NaN,Sun Dec 01 00:59:59 +0000 2019,NaN,NaN,NaN,1,1200942584731963392,LonestarAL,1.200942e+18,1.929842e+07,...,915,1973,8,"Concord, NC",Chris Adams üá∫üá∏ üèÅüêò üèà üèÄ,BamaC_1973,14839,NaN,NaN,False
39506,NaN,Sun Dec 01 00:59:59 +0000 2019,NaN,https://twitter.com/No_One909090/status/120094...,NaN,1,1200942585763770368,Kris10USA,1.200877e+18,3.142029e+08,...,27,162,0,the interwebs,No One,No_One909090,2028,NaN,NaN,False
39507,NaN,Sun Dec 01 00:59:59 +0000 2019,NaN,NaN,NaN,0,1200942586661425153,NaN,NaN,NaN,...,548,809,0,United States,cp6586,cparker6586,44343,NaN,NaN,False
39508,NaN,Sun Dec 01 00:59:59 +0000 2019,NaN,https://twitter.com/ea_neil/status/12009425853...,NaN,0,1200942585327620096,thehill,1.200892e+18,1.917731e+06,...,2046,1656,7,"New Jersey, USA",TakeUSAbackfromtRump,ea_neil,101800,NaN,NaN,False
39509,NaN,Sun Dec 01 00:59:59 +0000 2019,NaN,NaN,NaN,0,1200942585893806080,NaN,NaN,NaN,...,338,497,55,NaN,Ebeetle,Gunnyed,88436,NaN,NaN,False

In [4]:
#columns, i.e., variables
df.columns

Index(['coordinates', 'created_at', 'hashtags', 'media', 'urls',
       'favorite_count', 'id', 'in_reply_to_screen_name',
       'in_reply_to_status_id', 'in_reply_to_user_id', 'lang', 'place',
       'possibly_sensitive', 'quote_id', 'retweet_count', 'retweet_id',
       'retweet_screen_name', 'source', 'text', 'tweet_url', 'user_created_at',
       'user_id', 'user_default_profile_image', 'user_description',
       'user_favourites_count', 'user_followers_count', 'user_friends_count',
       'user_listed_count', 'user_location', 'user_name', 'user_screen_name',
       'user_statuses_count', 'user_time_zone', 'user_urls', 'user_verified'],
      dtype='object')

In [5]:
#Reviewing if tweet messages actually appear
df.text

0        @KamalaHarris Why is Trump mentioned by his la...
1        "The men and women of our military are totally...
2        @senatemajldr @realDonaldTrump Yeah, not like ...
3                 @realDonaldTrump #ImpeachTheMFTraitorNow
4        @realDonaldTrump Chocolate and Trump...two of ...
                               ...
39505    @LonestarAL @FunnyMaine @realDonaldTrump He di...
39506    @Kris10Marie627 @Brianjl61 @realDonaldTrump it...
39507    Just 8 work days left on Congress' calendar th...
39508    @thehill @realDonaldTrump https://t.co/hrDXvp1awP
39509    Just 8 work days left on Congress' calendar th...
Name: text, Length: 39510, dtype: object

In [6]:
#Total number of unique accounts in this dataset
n=len(pd.unique(df['user_screen_name']))
n

21890

In [7]:
#number of tweets per account
df.value_counts("user_screen_name")

user_screen_name
MariaAnnColeman    144
DebbieSVA           62
justjo2             38
McKechnieE          37
ChahtaYumi          34
                  ...
PoorLittlePoshG      1
PoorRichard1705      1
PopSmith783          1
PopeJohnSmith        1
zzyzyvasmay          1
Length: 21890, dtype: int64

In [8]:
#Filtering for @JoeBiden, @realDonaldTrump, @FoxNews, @CNN; only Joe Biden tweeted for this timeframe.
df.loc[df['user_screen_name'].isin(['JoeBiden','realDonaldTrump','FoxNews','CNN'])]

,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_user_id,...,user_followers_count,user_friends_count,user_listed_count,user_location,user_name,user_screen_name,user_statuses_count,user_time_zone,user_urls,user_verified
14124,NaN,Sun Dec 01 00:20:00 +0000 2019,NaN,NaN,NaN,50534,1200932522177122304,NaN,NaN,NaN,...,36167433,48,40086,"Washington, DC",Joe Biden,JoeBiden,8564,NaN,http://joebiden.com,True