In [1]:
# importing packages
import pandas as pd
import numpy as np
import os
import platform
import pingouin as pg
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels as sm
import pyreadstat

In [2]:
#opening file
df=pd.read_csv("PilotData/12012019/12012019_Merged.csv", low_memory=False)

In [3]:
#checking file
df

,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_user_id,...,user_followers_count,user_friends_count,user_listed_count,user_location,user_name,user_screen_name,user_statuses_count,user_time_zone,user_urls,user_verified
0,NaN,Sun Dec 01 00:00:02 +0000 2019,NaN,NaN,NaN,0,1200927498504200192,KamalaHarris,1.200536e+18,3.035499e+07,...,209,186,2,NaN,Diane Carrozza,DianeEllenC,13719,NaN,NaN,False
1,NaN,Sun Dec 01 00:00:01 +0000 2019,NaN,NaN,NaN,0,1200927496386035714,NaN,NaN,NaN,...,1473,3290,18,"Manhattan, NY",Things Trump Say,thingstrumpsay,154465,NaN,NaN,False
2,NaN,Sun Dec 01 00:00:00 +0000 2019,NaN,NaN,NaN,0,1200927489792626688,LeaderMcConnell,1.200774e+18,1.249982e+09,...,5,173,0,"Georgia, USA",AJS,AndrewJSheldon,209,NaN,NaN,False
3,NaN,Sun Dec 01 00:00:00 +0000 2019,ImpeachTheMFTraitorNow,NaN,NaN,0,1200927490434359300,realDonaldTrump,1.200918e+18,2.507388e+07,...,2246,2108,0,NaN,VAgirl,agirrrl,30890,NaN,NaN,False
4,NaN,Sun Dec 01 00:00:00 +0000 2019,NaN,NaN,NaN,0,1200927489821986817,realDonaldTrump,1.200869e+18,2.507388e+07,...,31,61,0,NaN,Catherine Schuchman,greyz67,1130,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591785,NaN,Sun Dec 01 23:59:57 +0000 2019,NaN,NaN,NaN,0,1201289867516424192,NaN,NaN,NaN,...,1939,0,2,Michigan,Michigan Tim,lmetiva,7446,NaN,NaN,False
591786,NaN,Sun Dec 01 23:59:59 +0000 2019,NaN,NaN,NaN,0,1201289875129094144,realDonaldTrump,NaN,2.507388e+07,...,5508,885,40,"Florida, USA",Mabry,cherrygunk,6352,NaN,https://linktr.ee/cherrygunk,False
591787,NaN,Sun Dec 01 23:59:56 +0000 2019,NaN,NaN,NaN,3,1201289862118170624,TaceyJean18,1.201289e+18,3.264432e+08,...,31055,3687,183,NaN,Aarika Rhodes,AarikaRhodes,23144,NaN,https://www.aarikaforcongress.com,True
591788,NaN,Sun Dec 01 23:59:58 +0000 2019,NaN,https://twitter.com/tuser5555/status/120128987...,NaN,87,1201289870888452097,TulsiGabbard,1.201288e+18,2.663735e+07,...,5076,5975,71,NaN,Myles tuser5555,tuser5555,328521,NaN,http://PETA.org,False
591789,NaN,Sun Dec 01 23:59:56 +0000 2019,QuidProJoe Joe30330 GeritolJoe CreepyUncleJoe ...,NaN,NaN,0,1201289861262663680,JoeBiden,1.200882e+18,9.390910e+05,...,12644,13594,3,"Garden City, KS",Thela 4#45,thela_45,90468,NaN,NaN,False

In [4]:
#columns, i.e., variables
df.columns

Index(['coordinates', 'created_at', 'hashtags', 'media', 'urls',
       'favorite_count', 'id', 'in_reply_to_screen_name',
       'in_reply_to_status_id', 'in_reply_to_user_id', 'lang', 'place',
       'possibly_sensitive', 'quote_id', 'retweet_count', 'retweet_id',
       'retweet_screen_name', 'source', 'text', 'tweet_url', 'user_created_at',
       'user_id', 'user_default_profile_image', 'user_description',
       'user_favourites_count', 'user_followers_count', 'user_friends_count',
       'user_listed_count', 'user_location', 'user_name', 'user_screen_name',
       'user_statuses_count', 'user_time_zone', 'user_urls', 'user_verified'],
      dtype='object')

In [5]:
#Reviewing if tweet messages actually appear
df.text

0         @KamalaHarris Why is Trump mentioned by his la...
1         "The men and women of our military are totally...
2         @senatemajldr @realDonaldTrump Yeah, not like ...
3                  @realDonaldTrump #ImpeachTheMFTraitorNow
4         @realDonaldTrump Chocolate and Trump...two of ...
                                ...
591785    Hunter Biden:\n\n-Married his brother’s widow....
591786                    @realDonaldTrump buffalo cracker?
591787    @TaceyJean18 @AndrewYang @Zach_Graumann @Paget...
591788    @TulsiGabbard I'm from the NorthEast so I know...
591789    @JoeBiden #QuidProJoe #Joe30330 #GeritolJoe #C...
Name: text, Length: 591790, dtype: object

In [6]:
#Total number of unique accounts in this dataset
n=len(pd.unique(df['user_screen_name']))
n

216616

In [7]:
#number of tweets per account
df.value_counts("user_screen_name")

user_screen_name
MariaAnnColeman    795
tuser5555          388
HenryLikesMath     329
GangUbi            236
chrislongview      222
                  ...
Rschafs60            1
Rshale13             1
RsnblOne             1
RsndyM               1
zzzz99797            1
Length: 216616, dtype: int64

In [8]:
#Filtering for @JoeBiden, @realDonaldTrump, @FoxNews, @CNN; only Joe Biden tweeted for this timeframe.
dfTarget=df.loc[df['user_screen_name'].isin(['JoeBiden','realDonaldTrump','FoxNews','CNN'])]
dfTarget

,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_user_id,...,user_followers_count,user_friends_count,user_listed_count,user_location,user_name,user_screen_name,user_statuses_count,user_time_zone,user_urls,user_verified
14124,NaN,Sun Dec 01 00:20:00 +0000 2019,NaN,NaN,NaN,50533,1200932522177122304,NaN,NaN,NaN,...,36168208,48,40085,"Washington, DC",Joe Biden,JoeBiden,8564,NaN,http://joebiden.com,True
302198,NaN,Sun Dec 01 14:40:39 +0000 2019,NaN,NaN,NaN,0,1201149111355006976,NaN,NaN,NaN,...,60153655,1105,156488,NaN,CNN,CNN,386154,NaN,http://www.cnn.com,True
460923,NaN,Sun Dec 01 19:48:00 +0000 2019,HIV WorldAIDSDay,NaN,https://medium.com/@JoeBiden/statement-from-vi...,2035,1201226459278385154,NaN,NaN,NaN,...,36169486,48,40082,"Washington, DC",Joe Biden,JoeBiden,8565,NaN,http://joebiden.com,True
523049,NaN,Sun Dec 01 21:45:00 +0000 2019,NaN,https://twitter.com/JoeBiden/status/1201255903...,NaN,9591,1201255903498002432,NaN,NaN,NaN,...,36169756,48,40082,"Washington, DC",Joe Biden,JoeBiden,8565,NaN,http://joebiden.com,True

In [9]:
dfTarget.value_counts("user_screen_name")

user_screen_name
JoeBiden    3
CNN         1
dtype: int64

In [10]:
dfTarget.text

14124     Eight years of Donald Trump will fundamentally...
302198    Sen. @amyklobuchar on whether there's any chan...
460923    Over the last 30 years, the fight against #HIV...
523049    Every voter counts. We need a president who is...
Name: text, dtype: object